import { BRANDING } from '@ecoswift/config/branding';

export default function PrivacyPolicyPage() {
  return (
    <section className="mx-auto max-w-3xl px-4 py-20 md:px-6 md:py-28">
      <h1 className="text-4xl font-bold tracking-tight md:text-5xl">Privacy Policy</h1>
      <p className="mt-4 text-sm text-muted-foreground">Last updated: July 30, 2026</p>

      <p className="mt-8 rounded-lg border border-border bg-muted/40 px-5 py-4 text-sm text-muted-foreground">
        {BRANDING.brandName} is a demonstration digital banking platform. This Privacy Policy is illustrative and describes,
        in general terms, how a platform like this would handle data. It does not reflect the practices of a licensed financial
        institution, and no real financial account or real funds are involved in the service this policy covers.
      </p>

      <div className="mt-10 space-y-10 text-base leading-relaxed text-foreground">
        <div>
          <h2 className="text-xl font-semibold tracking-tight">1. Information we collect</h2>
          <p className="mt-3 text-muted-foreground">
            When you use {BRANDING.brandName}, we may collect information you provide directly, such as your name, email
            address, and account details you enter during registration; information generated by your use of the platform, such as
            transaction activity, login timestamps, and device or session identifiers; and technical information collected
            automatically, such as IP address, browser type, and cookie identifiers.
          </p>
        </div>

        <div>
          <h2 className="text-xl font-semibold tracking-tight">2. Why we collect it</h2>
          <p className="mt-3 text-muted-foreground">We use the information we collect to:</p>
          <ul className="mt-3 list-disc space-y-2 pl-6 text-muted-foreground">
            <li>Create and secure your account, including authentication and multi-factor verification;</li>
            <li>Operate core platform features, such as deposits, withdrawals, and balance calculations;</li>
            <li>Maintain audit trails and security logs to detect misuse and protect platform integrity;</li>
            <li>Respond to support and contact requests;</li>
            <li>Improve the reliability, usability, and security of the platform.</li>
          </ul>
        </div>

        <div>
          <h2 className="text-xl font-semibold tracking-tight">3. How we use your information</h2>
          <p className="mt-3 text-muted-foreground">
            We use collected information only for the purposes described above and for other purposes that are compatible with them,
            such as troubleshooting, internal analytics on platform usage, and communicating important updates about the platform. We do
            not use your information to make real credit, lending, or financial decisions, since no real financial products are offered.
          </p>
        </div>

        <div>
          <h2 className="text-xl font-semibold tracking-tight">4. Cookies and similar technologies</h2>
          <p className="mt-3 text-muted-foreground">
            We use cookies and similar technologies to keep you signed in, remember your preferences (such as light or dark theme), and
            understand how the platform is used. You can control cookies through your browser settings; disabling them may affect some
            platform functionality, such as staying signed in.
          </p>
        </div>

        <div>
          <h2 className="text-xl font-semibold tracking-tight">5. How we share information</h2>
          <p className="mt-3 text-muted-foreground">
            We do not sell your personal information. We may share information with service providers who help us operate the
            platform (such as hosting and infrastructure providers), each bound by appropriate confidentiality obligations; when
            required by law, regulation, or valid legal process; or to protect the rights, safety, and security of {BRANDING.brandName},
            our users, or the public. Because this is a demonstration platform, we do not share data with real banking partners, payment
            networks, or credit bureaus.
          </p>
        </div>

        <div>
          <h2 className="text-xl font-semibold tracking-tight">6. Data retention</h2>
          <p className="mt-3 text-muted-foreground">
            We retain account and activity information for as long as your account remains active, and for a reasonable period
            afterward to comply with internal policies, resolve disputes, and enforce our agreements. As a demonstration environment,
            this platform may periodically be reset or purged, which can result in the deletion of account and transaction data
            without additional notice.
          </p>
        </div>

        <div>
          <h2 className="text-xl font-semibold tracking-tight">7. Your rights</h2>
          <p className="mt-3 text-muted-foreground">
            Depending on your location, you may have the right to access, correct, export, or delete the personal information we hold
            about you, and to object to or restrict certain processing. To exercise any of these rights, contact us using the details
            below and we will respond within a reasonable time.
          </p>
        </div>

        <div>
          <h2 className="text-xl font-semibold tracking-tight">8. Data security</h2>
          <p className="mt-3 text-muted-foreground">
            We apply reasonable technical and organizational measures to protect information on the platform, including encryption
            in transit, multi-factor authentication, device trust checks, and access controls. No method of transmission or storage is
            completely secure, and we cannot guarantee absolute security.
          </p>
        </div>

        <div>
          <h2 className="text-xl font-semibold tracking-tight">9. Children&apos;s privacy</h2>
          <p className="mt-3 text-muted-foreground">
            The platform is not directed at children, and we do not knowingly collect personal information from children. If you
            believe a child has provided us with personal information, please contact us so we can remove it.
          </p>
        </div>

        <div>
          <h2 className="text-xl font-semibold tracking-tight">10. Changes to this policy</h2>
          <p className="mt-3 text-muted-foreground">
            We may update this Privacy Policy from time to time to reflect changes to the platform. When we do, we will update
            the "Last updated" date at the top of this page. Material changes may also be communicated within the platform.
          </p>
        </div>

        <div>
          <h2 className="text-xl font-semibold tracking-tight">11. Contact us</h2>
          <p className="mt-3 text-muted-foreground">
            If you have questions about this Privacy Policy or how your information is handled, contact our privacy and security team
            at{' '}
            <a
              href={`mailto:${BRANDING.emails.security}`}
              className="font-medium text-primary underline-offset-4 hover:underline"
            >
              {BRANDING.emails.security}
            </a>
            .
          </p>
        </div>
      </div>
    </section>
  );
}
